" Automatically install plugins on first run
let vimPlugDir = $HOME.'/.vim/plugged'
if !isdirectory(vimPlugDir)
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Plugin list
call plug#begin(vimPlugDir)
Plug 'gruvbox-community/gruvbox'
Plug 'ntpeters/vim-better-whitespace'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'gabrielelana/vim-markdown'
Plug 'machakann/vim-highlightedyank'
" Plug 'tpope/vim-fugitive'
" Plug 'airblade/vim-gitgutter'
" Plug 'mhinz/vim-signify'
" TODO others:
" - highlighted yank
" - rename? or does coc do this
" - auto pairs
" - auto detect indentation
"       tpope/sleuth
"       ciaranm/detectindent
" - lang servers and similar (coc?)
" - commenter?
call plug#end()


" Colorscheme settings
syntax on
set background=dark
let g:gruvbox_contrast_dark='hard'
colorscheme gruvbox


" Remaps
let mapleader=" "
nnoremap <SPACE> <Nop>
nnoremap <leader>h <C-W><C-H>
nnoremap <leader>j <C-W><C-J>
nnoremap <leader>k <C-W><C-K>
nnoremap <leader>l <C-W><C-L>
noremap <leader>y "+y
noremap <leader>Y "+Y
noremap <leader>p "+p
noremap <leader>P "+P
nnoremap <silent><leader>f :Files<CR>
nnoremap <silent><leader>b :Buffers<CR>
nnoremap <silent><leader>g :Rg<CR>
nnoremap Q <Plug>(coc-rename)
" TODO coc remaps (go to def, etc.) with leader or g


" The rest of this file are random settings that I prefer

" Don't pretend to be vi
set nocompatible

" Disable the default Vim startup message
set shortmess+=I

" Show line numbers with relative line numbers
set number relativenumber

" Tune searching to fit my needs
set ignorecase incsearch "smartcase

" Enable spell-checking because I am notorious for mispells (get it?)
setlocal spell spelllang=en_us
set complete+=kspell
highlight SpellBad cterm=underline

" Tab settings (see http://vimcasts.org/episodes/tabs-and-spaces/)
set tabstop=8 softtabstop=4 shiftwidth=4 expandtab

" Indentation settings
set autoindent smartindent

" Fix the unintuitive behavior of backspace
set backspace=indent,eol,start

" Allow hidden buffers
set hidden

" Enable support for different filetypes
filetype plugin indent on

" Configure the way windows appear (always show status line and ruler)
set laststatus=2 ruler
setlocal colorcolumn=80

" Make CTRL-A & CTRL-X work as expected with numbers that start with 0
set nrformats-=octal

" Give a preview of what you are scrolling into
set scrolloff=4

" Enable mouse support (note: copy-paste achieved by holding shift)
set mouse+=a

" Open new windows to bottom and right
set splitbelow splitright

" Allow swap files, but change where they are stored
let swapDir = $HOME.'/.vim/swap-files'
if !isdirectory(swapDir)
    call mkdir(swapDir, 'p', 0700)
endif
let &directory = swapDir.'//,'.&directory

" Allow undo files, but change where they are stored
let &undodir = $HOME.'/.vim/undo-files'
if !isdirectory(&undodir)
    call mkdir(&undodir, 'p', 0700)
endif
set undofile

