[window]
opacity = 0.85
option_as_alt = "OnlyLeft"

[scrolling]
history = 100000

[font]
normal = { family = "Hack" }
size = 14

[[keyboard.bindings]]
key = "Escape"
mods = "Command"
action = "ToggleSimpleFullscreen"
