theme = "custom"

[editor]
line-number = "relative"
bufferline = "always"
rulers = [100]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

# https://docs.helix-editor.com/keymap.html
[keys.normal]
"X" = ["extend_line_up", "extend_to_line_bounds"]
C-s = ":w"
C-q = ":bc" # TODO map to :bc if >1 buffers are open, otherwise :q

[keys.insert]
C-space = "normal_mode"

[keys.select]
C-space = "normal_mode"
