theme = "custom"

[editor]
line-number = "relative"
bufferline = "always"
rulers = [100]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
C-s = ":w"
# TODO map ctrl-q to :bc if >1 buffers are open, otherwise :q
C-q = ":bc"

[keys.insert]
C-space = "normal_mode"

[keys.select]
C-space = "normal_mode"

# TODO minor mode for git?
# Probably with capital G since you can go to line # with gg anyways
